spring:
  application:
    name: biz-finance
#  liquibase:
#    enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql-dev.superbio.cn:13306/spbbase?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validation-query: SELECT 1
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://erueka-master.superbio.cn:8100/eureka/,http://erueka-slave.superbio.cn:8101/eureka/
    enabled: true
  instance:
    prefer-ip-address: true
swagger:
  enabled: true